services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: VERIFY_TOKEN
        value: my_secret_token_12345
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        value: 941401595727284